# Generated by Django 5.0.6 on 2024-07-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(default=1, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('dep_description', models.TextField()),
            ],
        ),
    ]
