# Generated by Django 5.0.6 on 2024-07-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('doc_spec', models.TextField()),
                ('doc_image', models.ImageField(default='default_image.jpg', upload_to='doctors')),
                ('dep_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hosp1.department')),
            ],
        ),
    ]
