# Generated by Django 5.0.6 on 2024-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp1', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
        ),
    ]
